/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "azqkguctispoctvmpmci"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6cWtndWN0aXNwb2N0dm1wbWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMTM4MTAsImV4cCI6MjA4NDU4OTgxMH0.cjn0-KOMMn-_K22j2k6kk37r5IAbPE9vpqFOKooWsIg"